
#ifndef KNOB
	#define KNOB(name,x,y,mintext,maxtext)
#endif
#ifndef SLIDER
#define SLIDER(name,x,y,mintext,maxtext)
#endif
#ifndef LEDBUTTON
	#define LEDBUTTON(name,x,y)
#endif
#ifndef LED
	#define LED(name,x,y)
#endif

#ifndef ENCODER
#define ENCODER(name,x,y)
#endif

#ifndef SCREEN
#define SCREEN(name,x,y,w,h)
#endif

#ifndef FADER
#define FADER(name,x,y)
#endif

KNOB(MASTER_TUNE, 1,1,"","")
LEDBUTTON(VCO1, 2.3,1)
KNOB(VCO1_Pitch, 3,1, "-2_oct","+2_oct")
KNOB(VCO1_PW, 4, 1, "", "")
LEDBUTTON(VCO4, 5.2, 1)
KNOB(VCO4_Pitch,6,1,"min","max")

KNOB(FM_1_to_2,1,2,"0","")
LEDBUTTON(VCO2,2.3,2)
KNOB(VCO2_Pitch,3,2,"-1/3d","+1/3d")
KNOB(VCO2_PW,4,2,"","")
LEDBUTTON(VCO5,5.2,2)
KNOB(VCO5_Pitch,6,2,"0","+3_oct")

KNOB(FM_2_to_3,1,3,"0","")
LEDBUTTON(VCO3,2.3,3)
KNOB(VCO3_Pitch,3,3,"-1/3d","+1/3d")
KNOB(VCO3_PW,4,3,"","")
LEDBUTTON(VCO6,5.2,3)
KNOB(VCO6_Pitch,6,3,"0","+3_oct")

LEDBUTTON(VCO7,5.2,4)
KNOB(VCO7_Pitch,6,4,"0","+3_oct")


LEDBUTTON(Interval_spread, 2.3, 4)
LEDBUTTON(Spread, 7, 4)

#define VCF1X 7.7
#define VCF1Y 1

KNOB(VCF1_Resonance,VCF1X,VCF1Y,"min","max")
LEDBUTTON(VCF1_ResonanceBut,VCF1X+0.2,VCF1Y+1)
LED(VCF1_O_L,VCF1X+0.5,VCF1Y-0.2)
KNOB(VCF1_Spectrum_Mod,VCF1X+1.5,VCF1Y,"0","")
LEDBUTTON(VCF1_Spectrum_ModBut,VCF1X+1.7,VCF1Y+1)

KNOB(VCF1_Frequency,VCF1X+0.75,VCF1Y + 1.5,"min","max")
LEDBUTTON(VCF1_FrequencyBut,VCF1X+0.2,VCF1Y+2.5)
LEDBUTTON(VCF1_Routing, VCF1X+1.7, VCF1Y + 2.5)

#define VCF2X 11
#define VCF2Y 1.1


KNOB(VCF2_Spectrum_mod,VCF2X,VCF2Y,"0","")
KNOB(VCF2_Feed_Back,VCF2X+1,VCF2Y,"0","")
KNOB(VCF2_Resonance,VCF2X+2,VCF2Y,"0","")
LED(VCF2_O_L,VCF2X+2.5,VCF2Y-0.2)

LEDBUTTON(VCF2_SPM,VCF2X +0.2,VCF2Y+1)
LEDBUTTON(VCF2_F_B,VCF2X + 0.2,VCF2Y+1.7)
LEDBUTTON(VCF2_RES,VCF2X + 0.2,VCF2Y+2.5)


#define BANKX 14.3
#define BANKY 1
KNOB(Bank_Low,BANKX,BANKY,"min","max")
KNOB(Bank_Mid_1,BANKX+1,BANKY,"min","max")
KNOB(Bank_Mid_2,BANKX+2,BANKY,"min","max")
KNOB(Bank_High,BANKX+3,BANKY,"min","max")

LEDBUTTON(LowButton,BANKX+0.8,BANKY+1)
LEDBUTTON(Mid1Button,BANKX+1.8,BANKY+1)
LEDBUTTON(Mid2BUtton,BANKX+2.8,BANKY+1)
LEDBUTTON(HighButton,BANKX+3.8,BANKY+1)


KNOB(Bank_Low_Level,BANKX,BANKY+1.5,"min","max")
KNOB(Bank_Mid_1_Level,BANKX+1,BANKY+1.5,"min","max")
KNOB(Bank_Mid_2_Level,BANKX+2,BANKY+1.5,"min","max")
KNOB(Bank_High_Level,BANKX+3,BANKY+1.5,"min","max")

LEDBUTTON(PB1but,BANKX+0.8,BANKY+2.5)
LEDBUTTON(PB2but,BANKX+1.8,BANKY+2.5)
LEDBUTTON(PB3but,BANKX+2.8,BANKY+2.5)
LEDBUTTON(PB4but,BANKX+3.8,BANKY+2.5)

#define AMPX 19
#define AMPY 1.5

LEDBUTTON(Cleanfeed_M_S,AMPX+0.5,AMPY+0.5)
KNOB(PAN_Cleanfeed,AMPX+1,AMPY,"L","R")
LEDBUTTON(VCF1_M_S,AMPX+2.5,AMPY+0.5)
KNOB(PAN_VCF1,AMPX+3,AMPY,"L","R")
LEDBUTTON(VCF2_M_S,AMPX+4.5,AMPY+0.5)
KNOB(PAN_VCF2,AMPX+5,AMPY,"L","R")

LEDBUTTON(Cleanfeed_VCA,AMPX+.5,AMPY+1.5)
KNOB(LEVEL_Cleanfeed,AMPX+1,AMPY+1,"L","R")
LEDBUTTON(VCF1_VCA,AMPX+2.5,AMPY+1.5)
KNOB(LEVEL_VCF1,AMPX+3,AMPY+1,"L","R")
LEDBUTTON(VCF2_VCA,AMPX+4.5,AMPY+1.5)
KNOB(LEVEL_VCF2,AMPX+5,AMPY+1,"L","R")

LEDBUTTON(Cleanfeed_FX,AMPX+1.2,AMPY+2.2)
LEDBUTTON(VCF1_FX,AMPX+3.2,AMPY+2.2)
LEDBUTTON(VCF2_FX,AMPX+5.2,AMPY+2.2)

KNOB(TOTAL_OUT, AMPX + 5, AMPY + 3, "min", "max")

#define ADSRX VCF2X
#define ADSRY 6

LEDBUTTON(ADSR,ADSRX-0.5,ADSRY+0.5)
KNOB(ADSR_A,ADSRX,ADSRY,"","")
KNOB(ADSR_D,ADSRX+1,ADSRY,"","")
KNOB(ADSR_S,ADSRX+2,ADSRY,"","")
KNOB(ADSR_R,ADSRX+3,ADSRY,"","")


#define ADX VCF2X-0.25
#define ADY 7

LEDBUTTON(AD,ADX-0.5,ADY+0.5)
KNOB(AD_A,ADX,ADY,"","")
KNOB(AD_D,ADX+1,ADY,"","")

#define LFOX ADX+2.5
#define LFOY ADY

LEDBUTTON(LFO, LFOX + 1.6, LFOY + 0.5)
KNOB(LFO_SPEED, LFOX, LFOY, "", "")
KNOB(LFO_SHAPE, LFOX + 1, LFOY, "", "")

LEDBUTTON(CHASE, 16, 4.6)
LEDBUTTON(STASH, 17, 4.6)

LEDBUTTON(CANCEL_LEFT, ADSRX-0.4, ADSRY-0.7)
LEDBUTTON(PARTIAL, ADSRX + 0.4, ADSRY - 0.7)
LEDBUTTON(FINAL, ADSRX+3 - 0.1, ADSRY - 0.7)
LEDBUTTON(CANCEL_RIGHT, ADSRX+3 + 0.7, ADSRY - 0.7)

LEDBUTTON(ZERO_LEFT, 1, 5.8)
LEDBUTTON(PORTAMENTO_LEFT, 2.7, 6)
LEDBUTTON(OCTUP_LEFT, 2.2, 6.5)
LEDBUTTON(OCTDOWN_LEFT, 1.7, 7)
LEDBUTTON(PORTAMENTO_RIGHT, 23, 6)
LEDBUTTON(OCTUP_RIGHT, 23.5, 6.5)
LEDBUTTON(OCTDOWN_RIGHT, 24, 7)

#define BROWX 3.5
#define BROWY 8
#define W 0.7
LEDBUTTON(LEFT_MOD, BROWX, BROWY-1)
LEDBUTTON(LEFT_UNAC, BROWX+1*W, BROWY - 1)
LEDBUTTON(LEFT_SUS, BROWX + 2 * W, BROWY - 1)
LEDBUTTON(RIGHT_1, BROWX, BROWY)
LEDBUTTON(RIGHT_2, BROWX+1*W, BROWY)
LEDBUTTON(RIGHT_3, BROWX + 2 * W, BROWY)
LEDBUTTON(RIGHT_4, BROWX + 3 * W, BROWY)
LEDBUTTON(RIGHT_5, BROWX + 4 * W, BROWY)
LEDBUTTON(RIGHT_6, BROWX + 5 * W, BROWY)
LEDBUTTON(RIGHT_7, BROWX + 6 * W, BROWY)
LEDBUTTON(RIGHT_8, BROWX + 7 * W, BROWY)
LEDBUTTON(RIGHT_MORE, BROWX + 8 * W, BROWY)
#undef BROWX
#define BROWX 16
LEDBUTTON(TARGET_LFO, BROWX+1, BROWY-1)
LEDBUTTON(TARGET_AD, BROWX + 1 + 1*W, BROWY - 1)
LEDBUTTON(TARGET_ADSR, BROWX + 1 + 2*W, BROWY - 1)
LEDBUTTON(RIGHT_VLFDIRT, BROWX + 5 * W, BROWY-1)
LEDBUTTON(RIGHT_MOD, BROWX + 6 * W, BROWY-1)
LEDBUTTON(RIGHT_UNAC, BROWX + 7 * W, BROWY-1)
LEDBUTTON(RIGHT_SUS, BROWX + 8 * W, BROWY-1)
LEDBUTTON(LEFT_MORE, BROWX, BROWY)
LEDBUTTON(LEFT_1, BROWX + 1 * W, BROWY)
LEDBUTTON(LEFT_2, BROWX + 2 * W, BROWY)
LEDBUTTON(LEFT_3, BROWX + 3 * W, BROWY)
LEDBUTTON(LEFT_4, BROWX + 4 * W, BROWY)
LEDBUTTON(LEFT_5, BROWX + 5 * W, BROWY)
LEDBUTTON(LEFT_6, BROWX + 6 * W, BROWY)
LEDBUTTON(LEFT_7, BROWX + 7 * W, BROWY)
LEDBUTTON(LEFT_8, BROWX + 8 * W, BROWY)
#undef BROWX

#define BROWX VCF2X+1.7
LEDBUTTON(VELOCITY, BROWX, BROWY-1)
LEDBUTTON(AT, BROWX, BROWY - 0.5)
LEDBUTTON(ZPRIME, BROWX, BROWY)
LEDBUTTON(X, BROWX - 3 * W, BROWY)
LEDBUTTON(Y, BROWX - 2 * W, BROWY)
LEDBUTTON(Z, BROWX - 1 * W, BROWY)
LEDBUTTON(KBCV, BROWX+1*W, BROWY)
LEDBUTTON(KBGATE, BROWX+2*W, BROWY)
LEDBUTTON(KBTRIG, BROWX+3*W, BROWY)
#undef BROWX
#undef W

#define SCREENX (VCF2X+0.8)
#define SCREENY (VCF2Y+1)

#define SCREENSIZE 2.0f

SCREEN(mainscreen,SCREENX,SCREENY, SCREENSIZE,(SCREENSIZE*(800.0f/480.0f)))
ENCODER(leftencoder,SCREENX-1,SCREENY+2)
ENCODER(rightencoder,SCREENX+2,SCREENY+2)


#define MIXER1X 4
#define MIXER1Y 5.5
#define W 0.7

SLIDER(MIXER_VCO1, MIXER1X, MIXER1Y, "", "")
SLIDER(MIXER_VCO2, MIXER1X+1*W, MIXER1Y, "", "")
SLIDER(MIXER_VCO3, MIXER1X+2*W, MIXER1Y, "", "")
SLIDER(MIXER_VCO4_7, MIXER1X+3*W, MIXER1Y, "", "")
SLIDER(MIXER_RM1_2, MIXER1X+4*W, MIXER1Y, "", "")
SLIDER(MIXER_NOISE_ANAWT, MIXER1X+5*W, MIXER1Y, "", "")
SLIDER(MIXER_NOISE_DIG, MIXER1X+6*W, MIXER1Y, "", "")
SLIDER(MIXER_NOISECOLOR, MIXER1X+7*W, MIXER1Y, "", "")


#define MIXER2X 16
#define MIXER2Y 5.5


SLIDER(MIXER_VCO4, MIXER2X, MIXER2Y, "", "")
SLIDER(MIXER_VCO5, MIXER2X + 1*W, MIXER2Y, "", "")
SLIDER(MIXER_VCO6, MIXER2X + 2*W, MIXER2Y, "", "")
SLIDER(MIXER_VCO7, MIXER2X + 3*W, MIXER2Y, "", "")
SLIDER(MIXER_SUMQUAD, MIXER2X + 4*W, MIXER2Y, "", "")
SLIDER(MIXER_RM2_3, MIXER2X + 5*W, MIXER2Y, "", "")
SLIDER(MIXER_NOISE_BROWN, MIXER2X + 6*W, MIXER2Y, "", "")
SLIDER(MIXER_NOISE_VIOLET, MIXER2X + 7*W, MIXER2Y, "", "")

#undef W

#undef SCREEN
#undef FADER
#undef ENCODER
#undef LEDBUTTON
#undef KNOB
#undef LED
#undef SLIDER