/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v1.0
processor: LPC54616J512
package_id: LPC54616J512BD100
mcu_data: ksdk2_0
processor_version: 3.0.1
functionalGroups:
- name: BOARD_InitPeripherals
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * SPI_2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SPI_2'
- type: 'flexcomm_spi'
- mode: 'SPI_Interrupt'
- type_id: 'flexcomm_spi_fa73bcfbc0a2fd3b8c6ba5b0b1f1446f'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM2'
- config_sets:
  - interrupt:
    - interrupt_sel: 'kSPI_RxLvlIrq kSPI_TxLvlIrq'
    - interrupt:
      - IRQn: 'FLEXCOMM2_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - quick_selection: 'QS_IRQ_priority1'
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveHigh'
      - phase: 'kSPI_ClockPhaseFirstEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '20000000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel0'
      - sselPol: 'kSPI_SpolActiveAllLow'
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '0'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t SPI_2_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveHigh,
  .phase = kSPI_ClockPhaseFirstEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 800000,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel0,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 0,
    .postDelay = 0,
    .frameDelay = 0,
    .transferDelay = 0
  }
};

void SPI_2_init(void) {
  RESET_PeripheralReset( kFC2_RST_SHIFT_RSTn);
  /* Enable interrupts */
  SPI_EnableInterrupts(SPI_2_PERIPHERAL, (kSPI_RxLvlIrq | kSPI_TxLvlIrq));
  /* Enable interrupt FLEXCOMM2_IRQn request in the NVIC */
  EnableIRQ(SPI_2_FLEXCOMM_IRQN);
  /* Initialization function */
  SPI_MasterInit(SPI_2_PERIPHERAL, &SPI_2_config, CLOCK_GetFreq(SPI_2_CLKSRC));
}

/***********************************************************************************************************************
 * SPI_5 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SPI_5'
- type: 'flexcomm_spi'
- mode: 'SPI_Interrupt'
- type_id: 'flexcomm_spi_fa73bcfbc0a2fd3b8c6ba5b0b1f1446f'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM5'
- config_sets:
  - interrupt:
    - interrupt_sel: 'kSPI_RxLvlIrq kSPI_TxLvlIrq'
    - interrupt:
      - IRQn: 'FLEXCOMM5_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - quick_selection: 'QS_IRQ_priority1'
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveHigh'
      - phase: 'kSPI_ClockPhaseFirstEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '20000000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel0'
      - sselPol: 'kSPI_SpolActiveAllLow'
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '0'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t SPI_5_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveHigh,
  .phase = kSPI_ClockPhaseFirstEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 800000,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel0,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 0,
    .postDelay = 0,
    .frameDelay = 0,
    .transferDelay = 0
  }
};

void SPI_5_init(void) {
  RESET_PeripheralReset( kFC5_RST_SHIFT_RSTn);
  /* Enable interrupts */
  SPI_EnableInterrupts(SPI_5_PERIPHERAL, (kSPI_RxLvlIrq | kSPI_TxLvlIrq));
  /* Enable interrupt FLEXCOMM5_IRQn request in the NVIC */
  EnableIRQ(SPI_5_FLEXCOMM_IRQN);
  /* Initialization function */
  SPI_MasterInit(SPI_5_PERIPHERAL, &SPI_5_config, CLOCK_GetFreq(SPI_5_CLKSRC));
}

/***********************************************************************************************************************
 * SPI_6 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SPI_6'
- type: 'flexcomm_spi'
- mode: 'SPI_Interrupt'
- type_id: 'flexcomm_spi_fa73bcfbc0a2fd3b8c6ba5b0b1f1446f'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM6'
- config_sets:
  - interrupt:
    - interrupt_sel: 'kSPI_RxLvlIrq kSPI_TxLvlIrq'
    - interrupt:
      - IRQn: 'FLEXCOMM6_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - quick_selection: 'QS_IRQ_priority1'
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveHigh'
      - phase: 'kSPI_ClockPhaseFirstEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '20000000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel0'
      - sselPol: 'kSPI_SpolActiveAllLow'
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '0'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t SPI_6_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveHigh,
  .phase = kSPI_ClockPhaseFirstEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 800000,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel0,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 0,
    .postDelay = 0,
    .frameDelay = 0,
    .transferDelay = 0
  }
};

void SPI_6_init(void) {
  RESET_PeripheralReset( kFC6_RST_SHIFT_RSTn);
  /* Enable interrupts */
  SPI_EnableInterrupts(SPI_6_PERIPHERAL, (kSPI_RxLvlIrq | kSPI_TxLvlIrq));
  /* Enable interrupt FLEXCOMM6_IRQn request in the NVIC */
  EnableIRQ(SPI_6_FLEXCOMM_IRQN);
  /* Initialization function */
  SPI_MasterInit(SPI_6_PERIPHERAL, &SPI_6_config, CLOCK_GetFreq(SPI_6_CLKSRC));
}

/***********************************************************************************************************************
 * SPI_7 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SPI_7'
- type: 'flexcomm_spi'
- mode: 'SPI_Interrupt'
- type_id: 'flexcomm_spi_fa73bcfbc0a2fd3b8c6ba5b0b1f1446f'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM7'
- config_sets:
  - interrupt:
    - interrupt_sel: 'kSPI_RxLvlIrq kSPI_TxLvlIrq'
    - interrupt:
      - IRQn: 'FLEXCOMM7_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - quick_selection: 'QS_IRQ_priority1'
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveHigh'
      - phase: 'kSPI_ClockPhaseFirstEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '20000000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel0'
      - sselPol: 'kSPI_SpolActiveAllLow'
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '0'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t SPI_7_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveHigh,
  .phase = kSPI_ClockPhaseFirstEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 800000,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel0,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 0,
    .postDelay = 0,
    .frameDelay = 0,
    .transferDelay = 0
  }
};

void SPI_7_init(void) {
  RESET_PeripheralReset( kFC7_RST_SHIFT_RSTn);
  /* Enable interrupts */
  SPI_EnableInterrupts(SPI_7_PERIPHERAL, (kSPI_RxLvlIrq | kSPI_TxLvlIrq));
  /* Enable interrupt FLEXCOMM7_IRQn request in the NVIC */
  EnableIRQ(SPI_7_FLEXCOMM_IRQN);
  /* Initialization function */
  SPI_MasterInit(SPI_7_PERIPHERAL, &SPI_7_config, CLOCK_GetFreq(SPI_7_CLKSRC));
}

/***********************************************************************************************************************
 * SPI_3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SPI_3'
- type: 'flexcomm_spi'
- mode: 'SPI_Interrupt'
- type_id: 'flexcomm_spi_fa73bcfbc0a2fd3b8c6ba5b0b1f1446f'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM3'
- config_sets:
  - interrupt:
    - interrupt_sel: 'kSPI_RxLvlIrq kSPI_TxLvlIrq'
    - interrupt:
      - IRQn: 'FLEXCOMM3_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - quick_selection: 'QS_IRQ_priority1'
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveHigh'
      - phase: 'kSPI_ClockPhaseFirstEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '20000000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel0'
      - sselPol: 'kSPI_SpolActiveAllLow'
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '0'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t SPI_3_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveHigh,
  .phase = kSPI_ClockPhaseFirstEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 800000,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel0,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 0,
    .postDelay = 0,
    .frameDelay = 0,
    .transferDelay = 0
  }
};

void SPI_3_init(void) {
  RESET_PeripheralReset( kFC3_RST_SHIFT_RSTn);
  /* Enable interrupts */
  SPI_EnableInterrupts(SPI_3_PERIPHERAL, (kSPI_RxLvlIrq | kSPI_TxLvlIrq));
  /* Enable interrupt FLEXCOMM3_IRQn request in the NVIC */
  EnableIRQ(SPI_3_FLEXCOMM_IRQN);
  /* Initialization function */
  SPI_MasterInit(SPI_3_PERIPHERAL, &SPI_3_config, CLOCK_GetFreq(SPI_3_CLKSRC));
}

/***********************************************************************************************************************
 * SCTimer_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SCTimer_1'
- type: 'sctimer'
- mode: 'basic'
- type_id: 'sctimer_11116c58643bd290f0e74db0acbc9466'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'SCT0'
- config_sets:
  - main:
    - config:
      - clockMode: 'kSCTIMER_System_ClockMode'
      - clockSelect: 'kSCTIMER_Clock_On_Rise_Input_0'
      - enableCounterUnify: 'true'
      - enableBidirection_l: 'false'
      - enableBidirection_h: 'false'
      - prescale_l: '8'
      - prescale_h: '1'
      - outInitState: ''
    - enableIRQ: 'true'
    - interrupt:
      - IRQn: 'SCT0_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - enableLTimer: 'false'
    - enableHTimer: 'false'
    - pwms: []
    - pwmMode: 'kSCTIMER_EdgeAlignedPwm'
    - pwmFrequency: '0'
    - events:
      - 0:
        - type: 'kSCTIMER_MatchEventOnly'
        - matchValue: '65535'
        - counter: 'kSCTIMER_Counter_L'
        - actions:
          - 0:
            - action: 'CounterLimit'
            - counter: 'kSCTIMER_Counter_L'
          - 1:
            - action: 'NextState'
            - nextState: '1'
      - 1:
        - type: 'kSCTIMER_MatchEventOnly'
        - matchValue: '65535'
        - counter: 'kSCTIMER_Counter_L'
        - actions:
          - 0:
            - action: 'CounterLimit'
            - counter: 'kSCTIMER_Counter_L'
          - 1:
            - action: 'NextState'
            - nextState: '0'
    - states:
      - 0:
        - events: 'event0'
      - 1:
        - events: 'event1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const sctimer_config_t SCTimer_1_initConfig = {
  .enableCounterUnify = true,
  .clockMode = kSCTIMER_System_ClockMode,
  .clockSelect = kSCTIMER_Clock_On_Rise_Input_0,
  .enableBidirection_l = false,
  .enableBidirection_h = false,
  .prescale_l = 7,
  .prescale_h = 0,
  .outInitState = 0
};
uint32_t SCTimer_1_event[2];

void SCTimer_1_init(void) {
  SCTIMER_Init(SCTIMER_1_PERIPHERAL, &SCTimer_1_initConfig);
  /* Initialization of state 0 */
  SCTIMER_CreateAndScheduleEvent(SCTIMER_1_PERIPHERAL, kSCTIMER_MatchEventOnly, 65535, kSCTIMER_Out_0, kSCTIMER_Counter_L, &SCTimer_1_event[0]);
  SCTIMER_SetupCounterLimitAction(SCTIMER_1_PERIPHERAL, kSCTIMER_Counter_L, SCTimer_1_event[0]);
  SCTIMER_SetupNextStateAction(SCTIMER_1_PERIPHERAL, 1, SCTimer_1_event[0]);
  SCTIMER_IncreaseState(SCTIMER_1_PERIPHERAL);
  /* Initialization of state 1 */
  SCTIMER_CreateAndScheduleEvent(SCTIMER_1_PERIPHERAL, kSCTIMER_MatchEventOnly, 65535, kSCTIMER_Out_0, kSCTIMER_Counter_L, &SCTimer_1_event[1]);
  SCTIMER_SetupCounterLimitAction(SCTIMER_1_PERIPHERAL, kSCTIMER_Counter_L, SCTimer_1_event[1]);
  SCTIMER_SetupNextStateAction(SCTIMER_1_PERIPHERAL, 0, SCTimer_1_event[1]);
  /* Enable interrupt SCT0_IRQn request in the NVIC */
  EnableIRQ(SCTIMER_1_IRQN);
}

/***********************************************************************************************************************
 * GPIO_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO_1'
- type: 'lpc_gpio'
- mode: 'GPIO'
- type_id: 'lpc_gpio_8c9ab9b3668a514c1f4609fe43001865'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO'
- config_sets:
  - lpc_gpio:
    - gpioConfig:
      - 0:
        - signal_number: 'PIO1.4'
        - pinDirection: 'kGPIO_DigitalInput'
        - outputLogic: '0U'
      - 1:
        - signal_number: 'PIO1.5'
        - pinDirection: 'kGPIO_DigitalInput'
        - outputLogic: '0U'
      - 2:
        - signal_number: 'PIO1.31'
        - pinDirection: 'kGPIO_DigitalOutput'
        - outputLogic: '1U'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
gpio_pin_config_t GPIO_1_config[3] = {
  {
    .pinDirection = kGPIO_DigitalInput,
    .outputLogic = 0U
  },
  {
    .pinDirection = kGPIO_DigitalInput,
    .outputLogic = 0U
  },
  {
    .pinDirection = kGPIO_DigitalOutput,
    .outputLogic = 1U
  }
};

void GPIO_1_init(void) {
  /* Initialize GPIO functionality on pin PIO1_4 */
  GPIO_PinInit(GPIO_1_GPIO, 1U, 4U, &GPIO_1_config[0]);
  /* Initialize GPIO functionality on pin PIO1_5 */
  GPIO_PinInit(GPIO_1_GPIO, 1U, 5U, &GPIO_1_config[1]);
  /* Initialize GPIO functionality on pin PIO1_31 */
  GPIO_PinInit(GPIO_1_GPIO, 1U, 31U, &GPIO_1_config[2]);
}

/***********************************************************************************************************************
 * SPI_8 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SPI_8'
- type: 'flexcomm_spi'
- mode: 'SPI_Interrupt'
- type_id: 'flexcomm_spi_fa73bcfbc0a2fd3b8c6ba5b0b1f1446f'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM8'
- config_sets:
  - interrupt:
    - interrupt_sel: 'kSPI_RxLvlIrq kSPI_TxLvlIrq'
    - interrupt:
      - IRQn: 'FLEXCOMM8_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - quick_selection: 'QS_IRQ_priority1'
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveHigh'
      - phase: 'kSPI_ClockPhaseFirstEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '500000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel0'
      - sselPol: 'kSPI_SpolActiveAllLow'
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '0'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
    - quick_selection: 'QS_SPI_1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t SPI_8_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveHigh,
  .phase = kSPI_ClockPhaseFirstEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 500000,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel0,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 0,
    .postDelay = 0,
    .frameDelay = 0,
    .transferDelay = 0
  }
};

void SPI_8_init(void) {
  RESET_PeripheralReset( kFC8_RST_SHIFT_RSTn);
  /* Enable interrupts */
  SPI_EnableInterrupts(SPI_8_PERIPHERAL, (kSPI_RxLvlIrq | kSPI_TxLvlIrq));
  /* Enable interrupt FLEXCOMM8_IRQn request in the NVIC */
  EnableIRQ(SPI_8_FLEXCOMM_IRQN);
  /* Initialization function */
  SPI_MasterInit(SPI_8_PERIPHERAL, &SPI_8_config, CLOCK_GetFreq(SPI_8_CLKSRC));
}

/***********************************************************************************************************************
 * USART_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'USART_1'
- type: 'flexcomm_usart'
- mode: 'interrupts'
- type_id: 'flexcomm_usart_fcc110cc6b16332e9dfd9e0df675e21f'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM1'
- config_sets:
  - interruptsCfg:
    - interrupts: ''
    - interrupt_vectors:
      - enable_rx_tx_irq: 'true'
      - interrupt_rx_tx:
        - IRQn: 'FLEXCOMM1_IRQn'
        - enable_priority: 'false'
        - enable_custom_name: 'false'
  - usartConfig_t:
    - usartConfig:
      - baudRate_Bps: '4000000'
      - parityMode: 'kUSART_ParityDisabled'
      - stopBitCount: 'kUSART_OneStopBit'
      - bitCountPerChar: 'kUSART_8BitsPerChar'
      - loopback: 'false'
      - txWatermark: 'kUSART_TxFifo0'
      - rxWatermark: 'kUSART_RxFifo1'
      - enableRx: 'true'
      - enableTx: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const usart_config_t USART_1_config = {
  .baudRate_Bps = 4000000,
  .parityMode = kUSART_ParityDisabled,
  .stopBitCount = kUSART_OneStopBit,
  .bitCountPerChar = kUSART_8BitsPerChar,
  .loopback = false,
  .txWatermark = kUSART_TxFifo0,
  .rxWatermark = kUSART_RxFifo1,
  .enableRx = true,
  .enableTx = true
};

void USART_1_init(void) {
  /* Reset FLEXCOMM device */
  RESET_PeripheralReset(kFC1_RST_SHIFT_RSTn);
  USART_Init(USART_1_PERIPHERAL, &USART_1_config, USART_1_CLOCK_SOURCE);
  USART_EnableInterrupts(USART_1_PERIPHERAL, 0);
  /* Enable interrupt FLEXCOMM1_IRQn request in the NVIC */
  EnableIRQ(USART_1_FLEXCOMM_IRQN);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  SPI_2_init();
  SPI_5_init();
  SPI_6_init();
  SPI_7_init();
  SPI_3_init();
  SCTimer_1_init();
  GPIO_1_init();
  SPI_8_init();
  USART_1_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
