/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO013_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO013_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO014_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO014_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO017_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO017_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO017_MODE_PULL_UP 0x02u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO018_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO018_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO024_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO024_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO025_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO025_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO027_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO027_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO028_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO028_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO08_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO08_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO110_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO110_FUNC_ALT2 0x02u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO117_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO117_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO121_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO121_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO122_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO122_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO123_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO123_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO124_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO124_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO125_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO125_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO126_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO126_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO127_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO127_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO128_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO128_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO129_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO129_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO130_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO130_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO13_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Pull-down.
 * Pull-down resistor enabled.
 */
#define PIO13_MODE_PULL_DOWN 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO18_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO18_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO19_FUNC_ALT0 0x00u

/*! @name PIO1_8 (number 36), T4
  @{ */
#define BOARD_INITPINS_T4_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_T4_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_T4_PIN 8U    /*!<@brief 1U pin index: 8 */
                                    /* @} */

/*! @name PIO1_21 (number 37), MK2
  @{ */
#define BOARD_INITPINS_MK2_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_MK2_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_MK2_PIN 21U   /*!<@brief 1U pin index: 21 */
                                     /* @} */

/*! @name PIO0_24 (number 38), T3
  @{ */
#define BOARD_INITPINS_T3_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_T3_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_T3_PIN 24U   /*!<@brief 0U pin index: 24 */
                                    /* @} */

/*! @name PIO1_9 (number 39), BR1
  @{ */
#define BOARD_INITPINS_BR1_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_BR1_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_BR1_PIN 9U    /*!<@brief 1U pin index: 9 */
                                     /* @} */

/*! @name PIO0_25 (number 40), T2
  @{ */
#define BOARD_INITPINS_T2_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_T2_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_T2_PIN 25U   /*!<@brief 0U pin index: 25 */
                                    /* @} */

/*! @name PIO0_27 (number 42), MK1
  @{ */
#define BOARD_INITPINS_MK1_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_MK1_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_MK1_PIN 27U   /*!<@brief 0U pin index: 27 */
                                     /* @} */

/*! @name PIO1_22 (number 43), T1
  @{ */
#define BOARD_INITPINS_T1_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_T1_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_T1_PIN 22U   /*!<@brief 1U pin index: 22 */
                                    /* @} */

/*! @name PIO0_28 (number 44), BR0
  @{ */
#define BOARD_INITPINS_BR0_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_BR0_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_BR0_PIN 28U   /*!<@brief 0U pin index: 28 */
                                     /* @} */

/*! @name PIO1_23 (number 46), T0
  @{ */
#define BOARD_INITPINS_T0_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_T0_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_T0_PIN 23U   /*!<@brief 1U pin index: 23 */
                                    /* @} */

/*! @name PIO1_17 (number 47), MK0
  @{ */
#define BOARD_INITPINS_MK0_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_MK0_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_MK0_PIN 17U   /*!<@brief 1U pin index: 17 */
                                     /* @} */

/*! @name PIO1_26 (number 63), MK3
  @{ */
#define BOARD_INITPINS_MK3_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_MK3_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_MK3_PIN 26U   /*!<@brief 1U pin index: 26 */
                                     /* @} */

/*! @name PIO0_8 (number 64), T6
  @{ */
#define BOARD_INITPINS_T6_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_T6_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_T6_PIN 8U    /*!<@brief 0U pin index: 8 */
                                    /* @} */

/*! @name PIO0_13 (number 67), BR3
  @{ */
#define BOARD_INITPINS_BR3_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_BR3_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_BR3_PIN 13U   /*!<@brief 0U pin index: 13 */
                                     /* @} */

/*! @name PIO1_27 (number 68), T7
  @{ */
#define BOARD_INITPINS_T7_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_T7_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_T7_PIN 27U   /*!<@brief 1U pin index: 27 */
                                    /* @} */

/*! @name PIO0_14 (number 69), MK4
  @{ */
#define BOARD_INITPINS_MK4_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_MK4_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_MK4_PIN 14U   /*!<@brief 0U pin index: 14 */
                                     /* @} */

/*! @name PIO0_17 (number 70), T2OLD
  @{ */
#define BOARD_INITPINS_T2OLD_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_T2OLD_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_T2OLD_PIN 17U   /*!<@brief 0U pin index: 17 */
                                       /* @} */

/*! @name PIO0_18 (number 72), BR4
  @{ */
#define BOARD_INITPINS_BR4_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_BR4_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_BR4_PIN 18U   /*!<@brief 0U pin index: 18 */
                                     /* @} */

/*! @name PIO1_28 (number 73), T0OLD
  @{ */
#define BOARD_INITPINS_T0OLD_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_T0OLD_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_T0OLD_PIN 28U   /*!<@brief 1U pin index: 28 */
                                       /* @} */

/*! @name PIO1_3 (number 60), RASPI_DETECT
  @{ */
#define BOARD_INITPINS_RASPI_DETECT_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_RASPI_DETECT_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_RASPI_DETECT_PIN 3U    /*!<@brief 1U pin index: 3 */
                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M4F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
